name: MMC5Dev
options:
  bundleIdPrefix: com.mmc5dev
  deploymentTarget:
    macOS: 14.0
packages:
  Shared:
    path: ../Shared
  ROMBuilder:
    path: ../MMC5Dev/Sources/ROMBuilder
targets:
  MMC5Dev:
    type: application
    platform: macOS
    sources:
      - path: Sources/MMC5Dev
      - path: Sources/MMC5Dev/Views
    dependencies:
      - package: Shared
      - package: ROMBuilder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mmc5dev.app
        DEVELOPMENT_TEAM: ""  # Add your team ID here if you have one
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "-"  # Use ad-hoc signing
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: 5.9
        ENABLE_HARDENED_RUNTIME: NO
    info:
      path: Sources/MMC5Dev/Info.plist
      properties:
        CFBundleName: MMC5Dev
        CFBundleDisplayName: MMC5Dev
        CFBundlePackageType: APPL
        CFBundleShortVersionString: 1.0.0
        CFBundleVersion: 1
        LSMinimumSystemVersion: 14.0
        NSHighResolutionCapable: true
        NSPrincipalClass: NSApplication
        LSUIElement: true
        CFBundleIconFile: AppIcon
        CFBundleIdentifier: com.mmc5dev.app
        CFBundleExecutable: MMC5Dev
        CFBundleDevelopmentRegion: en
        CFBundleInfoDictionaryVersion: 6.0
  MMC5DevUITests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests/MMC5DevUITests
    dependencies:
      - target: MMC5Dev
      - package: Shared
      - package: ROMBuilder
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.mmc5dev.ui-tests
        DEVELOPMENT_TEAM: ""  # Add your team ID here if you have one
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "-"  # Use ad-hoc signing
        SWIFT_VERSION: 5.9
        ENABLE_HARDENED_RUNTIME: NO
        TEST_TARGET_NAME: MMC5Dev
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/MMC5Dev.app/Contents/MacOS/MMC5Dev 